# Generated by Django 4.1.6 on 2023-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="suggestions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
