# Generated by Django 4.1.6 on 2023-03-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_appointment_prescription_appointment_suggestions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="suggestions", new_name="suggestion",
        ),
    ]
